### ISSUE TITLE
[Bug]: Dependencies are not correctly propagated to/by jest_test

### ISSUE THREAD

**Issue by mvukov** [aspect-build/rules_jest#72]
### What happened?

I am trying to use rules_jest with rules_ts. It looks to me that transitive deps are not correctly propagated to/by jest_test targets.

### Version

Development (host) and target OS/architectures: Ubuntu 20.04

Output of `bazel --version`: 5.2.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

* rules_ts: 1.0.2
* rules_jest: 0.12.1

Language(s) and/or frameworks involved: typescript

### How to reproduce

I made a simple example in https://github.com/oqton/rules_jest_ts_bug. Here is what a failure looks like:

```shell
bazel test //lib2:tests --test_output=all 
INFO: Analyzed target //lib2:tests (1 packages loaded, 11 targets configured).
INFO: Found 1 test target...
INFO: From Compiling TypeScript project //lib2:tests-ts [tsc -p lib2/tsconfig_tests-ts.json]:
WARNING: Running TsProject as a standalone process
Started a standalone process to perform this action but this might lead to some unexpected behavior with tsc due to being run non-sandboxed.
Your build might be misconfigured, try putting "build --strategy=TsProject=worker" into your .bazelrc or add "supports_workers = False" attribute into this ts_project target.
FAIL: //lib2:tests (see /home/mvukov/.cache/bazel/_bazel_mvukov/cd43fe90b7de779ab39217ab3aa39215/execroot/rules_jest_ts_bug/bazel-out/k8-fastbuild/testlogs/lib2/tests/test.log)
INFO: From Testing //lib2:tests:
==================== Test output for //lib2:tests:
FAIL lib2/lib2.test.js
  ● Test suite failed to run

    Cannot find module 'ts-md5' from 'node_modules/.aspect_rules_js/@oqton+lib1@0.0.0/node_modules/@oqton/lib1/index.js'

    Require stack:
      node_modules/.aspect_rules_js/@oqton+lib1@0.0.0/node_modules/@oqton/lib1/index.js
      lib2/index.js
      lib2/lib2.test.js

      2 | Object.defineProperty(exports, "__esModule", { value: true });
      3 | exports.decorateHash = void 0;
    > 4 | const lib1_1 = require("@oqton/lib1");
        |                ^
      5 | function decorateHash(s) {
      6 |     return ''.concat('11', (0, lib1_1.hashString)(s), '22');
      7 | }

      at Resolver._throwModNotFoundError (../jest/node_modules/.aspect_rules_js/jest-resolve@28.1.3/node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (node_modules/.aspect_rules_js/@oqton+lib1@0.0.0/node_modules/@oqton/lib1/index.js:4:18)
      at Object.require (lib2/index.js:4:16)
      at Object.require (lib2/lib2.test.js:3:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.756 s
Ran all test suites.
================================================================================
Target //lib2:tests up-to-date:
  bazel-bin/lib2/tests.sh
INFO: Elapsed time: 5.343s, Critical Path: 4.66s
INFO: 5 processes: 3 internal, 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 5 total actions
//lib2:tests                                                             FAILED in 2.7s
  /home/mvukov/.cache/bazel/_bazel_mvukov/cd43fe90b7de779ab39217ab3aa39215/execroot/rules_jest_ts_bug/bazel-out/k8-fastbuild/testlogs/lib2/tests/test.log

INFO: Build completed, 1 test FAILED, 5 total actions
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
This a dup of https://github.com/aspect-build/rules_ts/issues/268 so closing this to keep the discussion in a single place.
